apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio
  namespace: vallegrande
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicio
  template:
    metadata:
      labels:
        app: microservicio
    spec:
      containers:
      - name: microservicio
        image: diegoramos678/spring-test:latest
        resources:
          requests:
            cpu: "100m"  # Asignación de CPU
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        ports:
        - containerPort: 8080
