apiVersion: v1
kind: Service
metadata:
  name: microservicio
  namespace: vallegrande
spec:
  selector:
    app: microservicio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
